### ISSUE TITLE
SSR shows an warning with useLayoutEffect

### ISSUE THREAD

**Issue by coderdiaz** [medipass/react-payment-inputs#14]
I'm using this package with Next.js and works awesome but this shows an warning in `dev`mode because `useLayoutEffect` is used only for client-side applications for SSR application is better use `useEffect` according to documentation.

Any suggestion for solve this warning?

![image](https://user-images.githubusercontent.com/1901273/64494158-ef903c00-d24e-11e9-9625-cc289415c334.png)

**Comment by sanchan** [comment]
This may be not related to `react-payment-inputs`, but to React itself, actually they explain this in their documentation:

> If you use server rendering, keep in mind that neither useLayoutEffect nor useEffect can run until the JavaScript is downloaded. **This is why React warns when a server-rendered component contains useLayoutEffect**.


https://reactjs.org/docs/hooks-reference.html#uselayouteffect

**Comment by ericmerl** [comment]
I was able to work around this warning by wrapping the component that uses the library in a `typeof window !== 'undefined'` statement, which prevents it from being rendered on the server.
