### ISSUE TITLE
Allow modifying placeholder text

### ISSUE THREAD

**Issue by ronen-agranat** [medipass/react-payment-inputs#15]
Currently, the error message text can easily be specified, for translations, for example.

However, the placeholder text is hardcoded.

If it were possible to override the placeholder text in the same way that is currently possible for the error message text, then that would make it much easier to provide localisation.

**Comment by jxom** [comment]
Sure. You can do that by passing the `placeholder` attribute to the `<input>` element:

```
<input {...getCardNumberProps()} placeholder="Card number" />
```
